### ISSUE TITLE
Save logs in .log extension

### ISSUE THREAD

**Issue by misa-coder** [Skillz4Killz/Discordeno#102]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to see a complete logs but not able to see because of my vps. Whenever it restarts it clear the console values.

**Describe the solution you'd like**
If logger save all the logs passed through it in a .log extension like Winston then it will be great.

**Additional context**
Not really a must feature but it will be a cool feature available here.

**Comment by chroventer** [comment]
The logger itself is unrelated to Discordeno. I think adding such functionality would be a bloat and is unrelated to the module.

Check out Houston which supports Winston-like features:
https://deno.land/x/houston

**Comment by misa-coder** [comment]
I know it's not directly related to discordeno. But logger is one of it's function [available here](https://github.com/Skillz4Killz/Discordeno/blob/master/src/utils/logger.ts). So I recommended enhancement in that function. Maybe it's better to use Houston for now. Thanks for your recommendation.

**Comment by Skillz4Killz** [comment]
@misa-coder This is a neat idea but i think i would agree with Chroventer. TBH the only reason I added those logger functions was for me to debug stuff while I was building this(perhaps it's time i remove this). I'm not sure anyone should use it outside(in your bots when there are much better loggers out there). https://deno.land/x/logger@v1.0.0

In my opinion, the best logging system for a Discord bot is to log them in Discord itself as opposed to a file. When you deploy your code to production, you won't check your vps files daily but you will check Discord daily. You can even set up @ mentions to alert you for critical errors. Can't do that with a file system. 

Create a couple of channels on your bots support server and make some webhooks for them. Send a message to those webhooks whenever you need to log something. This works best for most logging system where you want to fix errors. This is what I am doing on my bot.
