### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by Skillz4Killz** [Skillz4Killz/Discordeno#105]
**Is your feature request related to a problem? Please describe.**
One of the big things missing in Discordeno, that I would like to have is Unit Testing. 

**Describe the solution you'd like**
I want our unit testing to be very different from anything I have ever seen done in some others where they create a mock response for an api call. Ideally, I want our unit testing to be testing the actual api and not mocking it. Mocks although will make it faster make it unreliable and increases the load to maintain.

1. Store a bot token in a github secret.
2. Then using the CI i would try and run the bot which will be in a private test server that will trigger each & every function i want tested.
3. Start by creating a new guild which gives it a fresh new clean environment.
4. Create a role with custom options. (Review the roles structure to ensure it is accurate to the options we provided.)
5. Create 1 channel for each channel type.
6. Create a channel with a custom user permissions
7. Create a channel with a custom role permission
8... Etc... In essence the goal is to have every part of the lib tested with 100% confidence.

My only concern is testing like 100s of things can take time and it may cause the CI to take time determining if the build passes. However, i feel like having enough confidence to merge by waiting a few minutes before merging a PR would be worth it.

Note: Due to the amount of things that need to be done, the CI should only run when merging a PR to master branch.

**Describe alternatives you've considered**
- Mock API

**Additional context**
https://deno.land/manual/testing

**Comment by chroventer** [comment]
> My only concern is testing like 100s of things can take time and it may cause the CI to take time determining if the build passes. However, i feel like having enough confidence to merge by waiting a few minutes before merging a PR would be worth it.

One of the many concerns is API ratelimits. We will have to create a queue system that will add more time to the CI.

**Comment by Skillz4Killz** [comment]
@chroventer That is 100% right but it will also help test the rate limiter. I don't think we need to create a queue system. The rate limiter should be doing it and this is also a way to test how good the rate limiting system works. 

Ideally, these tests should only be run when a major PR is going to be merged to `stable` branch. For example, we should always be coding working on `master` all prs are sent to `master` but when it is time to release as in updating the stable we should always run these tests to make sure nothing is going to break. And i don't mind waiting a lil while to update/deploy a major PR to the main stable version. 

This way most PR's should not take long to review/merge.

For example, think of #100 this is a major change and it would be nice to know that every function is still working properly with the new Discord v8 API when deploying this live.

**Comment by chroventer** [comment]
- [x] getMessage()
- [x] sendMessage()
- [x] editChannel()
