### ISSUE TITLE
channelOverwriteHasPermission Unit Testing

### ISSUE THREAD

**Issue by Skillz4Killz** [Skillz4Killz/Discordeno#115]
**Is your feature request related to a problem? Please describe.**
Add a unit test for channelOverwriteHasPermission function which can be found inside the src/handlers/channel.ts file.

**Describe the solution you'd like**
1. Create a new role
2. Create a channel with a set of permissions being granted and denied to this role
3. Check if this role has a permission in this channel overwrite
4. confirm that it denies permission for a permission the role does not have
5. Check if it also denies for a permission that was neither granted nor denied

**Additional context**
Please send PR to #109

**Comment by chroventer** [comment]
#120
