### ISSUE TITLE
Error in docs

### ISSUE THREAD

**Issue by Suyashtnt** [Skillz4Killz/Discordeno#136]
**Describe the bug**
In the docs a table is displayed incorrectly

**To Reproduce**
1. Go to https://discordeno.netlify.app/gettingstarted#exampleusage
2. Look at Open Source bots

**Expected behavior**
It to display correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/45307955/95676764-eba4bb00-0bc0-11eb-956f-63752aa55a84.png)

**Additional context**
Might be linked to #134

**Comment by chroventer** [comment]
Hmm,,, when viewed using the GitHub file viewer, it displays the table correctly.

**Comment by Suyashtnt** [comment]
And that’s the weird part

**Comment by Skillz4Killz** [comment]
Fixed it was just missing a empty line before the table

![image](https://user-images.githubusercontent.com/23035000/95768487-6be02480-0c84-11eb-9d48-8cefc68997c3.png)
