### ISSUE TITLE
Sharding Manager

### ISSUE THREAD

**Issue by Skillz4Killz** [Skillz4Killz/Discordeno#15]
We need a sharding manager.

My current thoughts on sharding is that **ALL BOTS ARE SHARDED BOTS**. There is no such thing as a non-sharded bot. Bot's under 1000 server can simply be placed in 1 shard. There is so much confusion for devs especially beginner developers around sharding or not sharding. By default, we will make all bots sharded to the recommended options that discord provides on initial connection.

We can take inspiration from Eris built in sharder and build a similar sharding solution. If and when a bot reaches a milestone like 25K servers we can help them use a custom sharding solution. That can bebuilt post v1? Basically imagine a eris-sharder but built into the lib in some way. As an official sharding solution for larger bots.

**last note:** At this time, deno has no support for clusters so im not sure how wed handle this yet at all. Should wait for deno to implement it i believe

**Comment by resynth1943** [comment]
Looks like we'd have to wait then. :thinking: Do you have any other solutions?

**Comment by Skillz4Killz** [comment]
@resynth1943 At the moment, no. Once I finish the rest of the stuff and sharding is the last thing left, I can try and start a convo with the deno devs about it and see if they can implement clusters or maybe they can have a better alternative solution

**Comment by Skillz4Killz** [comment]
Deno team recommends checking out Web Workers for this.

**Comment by Skillz4Killz** [comment]
Sharding is now working and the bot loadded up on all 6 shards and received all the guild creates. Gotta work on working on rate limiting.
