### ISSUE TITLE
[Docs] Velociraptor Installation Guide

### ISSUE THREAD

**Issue by Skillz4Killz** [Skillz4Killz/Discordeno#157]
**Is your feature request related to a problem? Please describe.**
Velociraptor would be very nice to teach how to install as it allows them to just do `vr start` instead of typing out the entire massive flags list to run the code.

**Describe the solution you'd like**
A simple guide showing how to install velociraptor for you.

**Describe alternatives you've considered**
Denon???

**Additional context**
N.A

**Comment by ayntee** [comment]
Again, this is irrelevant to the guide. Perhaps, we can add a redirect link to Velociraptor's installation page.

**Comment by vintprox** [comment]
https://github.com/denosaurs/denon
```ts
import { DenonConfig } from "https://deno.land/x/denon@2.4.5/mod.ts";
import { config as configureEnv } from "https://deno.land/x/dotenv@v1.0.1/mod.ts";

/**
 * 1. Create .env.example with the BOT_TOKEN key empty.
 * 2. Copy it to .env and insert token there.
 * 3. Add ".env" line to .gitignore
 * 4. Pass token to createClient with:
      ...
      token: Deno.env.get("BOT_TOKEN")!
      ...
 */
const env = configureEnv({
  safe: true,
});

const config: DenonConfig = {
  env,
  lock: "lock.json",
  log: env.LOG_LEVEL,
  scripts: {
    start: {
      cmd: "src/bot.ts",
      desc: "Start the bot",
      allow: {
        env: true,
        net: true,
      },
    },
    lock: {
      cmd: "deno cache --lock-write src/bot.ts",
      desc: "Lock dependencies for integrity checking",
    },
  },
};

export default config;
```

```sh
$ denon start
```

**Comment by ayntee** [comment]
> https://github.com/denosaurs/denon
> 
> ```ts
> import { DenonConfig } from "https://deno.land/x/denon@2.4.5/mod.ts";
> import { config as configureEnv } from "https://deno.land/x/dotenv@v1.0.1/mod.ts";
> 
> /**
>  * 1. Create .env.example with the BOT_TOKEN key empty.
>  * 2. Copy it to .env and insert token there.
>  * 3. Add ".env" line to .gitignore
>  * 4. Pass token to createClient with:
>       ...
>       token: Deno.env.get("BOT_TOKEN")!
>       ...
>  */
> const env = configureEnv({
>   safe: true,
> });
> 
> const config: DenonConfig = {
>   env,
>   lock: "lock.json",
>   log: env.LOG_LEVEL,
>   scripts: {
>     start: {
>       cmd: "src/bot.ts",
>       desc: "Start the bot",
>       allow: {
>         env: true,
>         net: true,
>       },
>     },
>     lock: {
>       cmd: "deno cache --lock-write src/bot.ts",
>       desc: "Lock dependencies for integrity checking",
>     },
>   },
> };
> 
> export default config;
> ```
> 
> ```shell
> $ denon start
> ```

Is it relevant to the issue?

**Comment by vintprox** [comment]
> Is it relevant to the issue?

Just pointing out obvious: there are only more tools.

**Comment by ayntee** [comment]
> > Is it relevant to the issue?
> 
> Just pointing out obvious: there are only more tools.

Appreciate the suggestion, but closing this since a guide for third-party tools would be irrelevant and off-topic to *Discordeno*.
