### ISSUE TITLE
moveMember Function

### ISSUE THREAD

**Issue by Skillz4Killz** [Skillz4Killz/Discordeno#164]
**Is your feature request related to a problem? Please describe.**
Although the ability to move members does exist in DD, we should have a simpler way to do it. For example, at the moment you have to `editMember(guildID, memberID, { channel_id: newChannelID }, 'reason');`

**Describe the solution you'd like**
`moveMember(memberID, channelID, reason)` 

When a user wants to move a member the first thing they type is move and VSC autocomplete would help here a lot.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ayntee** [comment]
On it!
