### ISSUE TITLE
RESUME Functionality

### ISSUE THREAD

**Issue by Skillz4Killz** [Skillz4Killz/Discordeno#17]
**Is your feature request related to a problem? Please describe.**
Sometimes Discord API disconnects on occassion and we need to use the RESUME functionality to reinitiate a connection without losing any of the events from the last one being received. I have already finalized the `s` sequence number counter.

**Describe the solution you'd like**
Use Discords RESUME functionality

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by resynth1943** [comment]
I'll take a look. Thank you.

**Comment by Skillz4Killz** [comment]
Should be implemented now but we need a way to set it in an interval to retry every 10 seconds or so until it reconnects and if discord responds with an error it should start over with a new identify

**Comment by Skillz4Killz** [comment]
I believe this is now done! Needs testing on a live bot of how the RESUME handles and works over time.
