### ISSUE TITLE
 Compression

### ISSUE THREAD

**Issue by Skillz4Killz** [Skillz4Killz/Discordeno#18]
**Is your feature request related to a problem? Please describe.**
We should enable the ability to have GZIP compression from discord to decrease bandwidth used when sending data

**Describe the solution you'd like**
I think Deno implemented gzip compression
https://github.com/denoland/deno/pull/3597

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Yofou** [comment]
I saw this on deno.land https://deno.land/x/wasm_gzip@v1.0.0

might be what you're looking for

**Comment by Skillz4Killz** [comment]
Nice, ill keep that in mind. Since its a bit new and untested id prefer to give it some time to have other users test it thoroughly find any bugs etc

**Comment by TTtie** [comment]
No, it isn't. For `zlib-stream` compression, you need to use `zlib-stream` compression, which requires a shared zlib context - which `wasm_gzip` doesn't provide.

**Comment by Skillz4Killz** [comment]
> No, it isn't. For `zlib-stream` compression, you need a shared zlib context - which `wasm_gzip` doesn't provide.

Ahh good catch!

**Comment by TTtie** [comment]
For regular compression though (`compress = true` in `IDENTIFY`), no shared context is needed.

**Comment by chroventer** [comment]
Just found this: https://deno.land/x/zlib.es@v1.0.0

**Comment by Skillz4Killz** [comment]
oo nice, @TTtie have u had a chance to take a look at this, could we use this for compression stuff?

**Comment by TTtie** [comment]
For packet-based decompression, yes it should: https://github.com/Denocord/Denocord/commit/d729b7169acaa1d1db9f027586a1a96f3d3934a2

**Comment by Skillz4Killz** [comment]
Closed in #100
