### ISSUE TITLE
errorChannelID working

### ISSUE THREAD

**Issue by Dduvacher** [Skillz4Killz/Discordeno#183]
I was wondering if the errorChannelID in the config.ts works automatically.
I''ve put a channel ID in it but when my bot gets an error it doesn't send any message in the chan.
I've setup a try catch to send a message to this chan and it works.
However on my console I've a pretty self-explained message `{ message: "Cannot send an empty message", code: 50006}` but I don't know how to retrieve it because the error in my catch is only `REQUEST_CLIENT_ERROR`.
Do you know how can I get informations like the printing in my console ?

**Comment by Skillz4Killz** [comment]
It is not enabled by default to prevent spam when developers are starting but that should probably change as errors are too helpful. This option was mostly meant for production bots as opposed to the local dev bots. Nonetheless, I will have this updated in the near future. 

You can add this your self by going to the events/debug file and just sending a message to that error channel
