### ISSUE TITLE
Is there a way to retrieve message reactions ?

### ISSUE THREAD

**Issue by Dduvacher** [Skillz4Killz/Discordeno#184]
I think by default reactions are not provided when I get my message. (I didn't find it when I print messages)

**Comment by ayntee** [comment]
Can you provide some more details?

**Comment by ayntee** [comment]
You can use the function *getMessage* to get the entire message object and then obtain message reactions by `Message.reactions`.

![image](https://user-images.githubusercontent.com/34645569/99076720-08277f00-25d5-11eb-8624-f84c352de078.png)

**Comment by Dduvacher** [comment]
Yes of course sorry.
I'm trying to implement a kind of lotery.
So the bot say a message, people add reactions.
And when I say go or something, I want to get all the reactions of my message.
Actually when I retrieve my message there is no reactions field in my message object.

```
const sentMessage = await sendMessage(message.channelID, 'Qui veut s'inscrire');
await addReaction(message.channelID, sentMessage.id, ":point_up:");
const goTirage = await needMessage(message.author.id, message.channelID);
console.log('sentMessage', sentMessage);
```

**Comment by Dduvacher** [comment]
Ok I'm so stupid.
Of course there is no reactions because of my message in my const is the old one
So sorry for distubring.

**Comment by ayntee** [comment]
> Yes of course sorry.
> I'm trying to implement a kind of lotery.
> So the bot say a message, people add reactions.
> And when I say go or something, I want to get all the reactions of my message.
> Actually when I retrieve my message there is no reactions field in my message object.
> 
> ```
> const sentMessage = await sendMessage(message.channelID, 'Qui veut s'inscrire');
> await addReaction(message.channelID, sentMessage.id, ":point_up:");
> const goTirage = await needMessage(message.author.id, message.channelID);
> console.log('sentMessage', sentMessage);
> ```

You can use the *reactionAdd* event to "track" the user reactions.
![image](https://user-images.githubusercontent.com/34645569/99077011-84ba5d80-25d5-11eb-84c4-68b6041fc01a.png)

**Comment by Dduvacher** [comment]
I think my reactionAdd event is not working ...
If I put a console.log in the function nothing happen when I react to a message.

On the official boilerplate, my reactionAdd.ts looks like:
```
botcache.eventHandlers.reactionAdd = function (message, emoji, userID) {
console.log("test");
processReactionCollectors(message, emoji, userID);
}
```

**Comment by Skillz4Killz** [comment]
@Dduvacher Please make sure that you have the reaction intents enabled in your mod.ts file. Also if you are looking to get reaction and not a new message you probably want the `needReaction` function

**Comment by ayntee** [comment]
Reference: ![image](https://user-images.githubusercontent.com/34645569/99079357-46bf3880-25d9-11eb-9f9b-791eced587c3.png)
