### ISSUE TITLE
Custom Caching

### ISSUE THREAD

**Issue by Skillz4Killz** [Skillz4Killz/Discordeno#19]
**Is your feature request related to a problem? Please describe.**
I think a way to have a custom cache would be incredible. For example, if i could implement Redis to store my cache.

**Describe the solution you'd like**
A cache provider perhaps that will accept methods for stuff like get set etc and then modify all the cache places.

**Describe alternatives you've considered**
NA

**Additional context**
Guild Member Update and Guild Member Remove issues found on Eris lib with intents.

**Comment by chroventer** [comment]
Can you elaborate on this?

**Comment by Skillz4Killz** [comment]
Closed in #100
