### ISSUE TITLE
Bot not starting up due to "[ERROR]: 'type' is specified more than once"

### ISSUE THREAD

**Issue by NTMNathan** [Skillz4Killz/Discordeno#21]
**Describe the bug**
So, i've created my own bot with Discordeno based from the template you have provided and customised it with my own liking. I've installed the newly released latest Deno Version, TypeScript and Discordeno version. However, when booting up the bot with the `deno run --allow-read --unstable mod.ts` or without the `--unstable`. I have ran into an error which resulted in:

```
ntmnathan:DenoBot ntmnathan$ deno run --allow-net --allow-read --unstable mod.ts
Compile file:///Users/ntmnathan/Documents/DenoBot/mod.ts
error: TS2783 [ERROR]: 'type' is specified more than once, so this usage will be overwritten.
          type: options.type ? ChannelTypes[options.type] : undefined,
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/Skillz4Killz/Discordeno/v1/structures/guild.ts:85:11

    This spread always overwrites this property.
              ...options,
              ~~~~~~~~~~
        at https://raw.githubusercontent.com/Skillz4Killz/Discordeno/v1/structures/guild.ts:93:11
```

I am not 100% sure if this is on my end or Discordeno's. Any help appreciated.

**To Reproduce**
Steps to reproduce the behaviour:
1. Execute `deno run --allow-net --allow-read --unstable mod.ts`
2. Error above will be produced

**Expected behaviour**
If the `deno` command above is executed in the bash console, it should make the bot authenticate with the API and go online. 

**Resources**
If you want me to add screenshots/code. Let me know, but its similar to Discordeno example.

**Additional context**
None.

**Comment by NTMNathan** [comment]
Seems like its fixed from this pull request: https://github.com/Skillz4Killz/Discordeno/pull/22

**Comment by Skillz4Killz** [comment]
@NTMNathan Merged #22 Let me know if you still see any issues please

**Comment by NTMNathan** [comment]
Sure, as of now, the bot started and commands work as expected. 

 Also I am having some problems (still learning as im new to Discordeno) with getting the Author/OtherUser Avatar URL and mentions:

- Whats the correct way to define the Avatar for an Author (me) or another user with image size, format, dynamic image etc.?
- How would I work out mentions? (E.g. Mention user for hug command)

Thanks again

**Comment by Skillz4Killz** [comment]
> * Whats the correct way to define the Avatar for an Author (me) or another user with image size, format, dynamic image etc.?

@NTMNathan There was a small `/` typo in the avatarURL value but that is now fixed if you do `deno cache --reload mod.ts` it should fix itself.

`user.avatarURL()` => Default settings
`user.avatarURL(2048)` => Default image format with size of 2048
`user.avatarURL(2048, 'jpg')` => JPG image format with size of 2048

> * How would I work out mentions? (E.g. Mention user for hug command)

Discordeno provides you a `message.mentions` property which has all User objects for any users that were mentioned. So if for example you wanted to do a hug command you could do

```ts
const user = message.mentions.length ? message.mentions[0] : message.author
```
This would use the first mentioned user or if none were provided it would use the message author itself.

As an example, I just pushed a simple avatar command showing both these in action:
https://github.com/Skillz4Killz/Discordeno-bot-template/blob/master/src/commands/avatar.ts
![image](https://user-images.githubusercontent.com/23035000/82080142-062a4500-96b2-11ea-86f6-86438b26d368.png)

![image](https://user-images.githubusercontent.com/23035000/82080081-f1e64800-96b1-11ea-979f-b724daa91739.png)

Note: i am going to close this issue as the bug related to this issue has been closed, if you have any more questions or bugs feel free to open as many issues as you like
