### ISSUE TITLE
Snake Case

### ISSUE THREAD

**Issue by Skillz4Killz** [Skillz4Killz/Discordeno#25]
Hello 👋 

A few users have noted that they see some odd instances of snake case in the library and I wanted to take a minute to address it. 

When I started this library my goal was to learn different things and try different things. Most of what I did in this lib is for me to experiment and learn. I realized how terrible it was to work with snake_case. This became quite problematic to use in the long run so I opted for camelCase. If I missed any that are still in snake_case I will 100% be correcting them.

If you see any please leave them in a comment below, I will keep this issue pinned for a while.

Note: Since this will be changing the public API for some methods/props, we will be making this as v2 branch once all of them have been fixed.

**Comment by resynth1943** [comment]
So are we just camelCasing everything?

**Comment by Skillz4Killz** [comment]
@resynth1943 Yes snake case became way too difficult to use for me. The more i coded with it the less i enjoyed it and i just never got used to coding it that way. It also makes having to type another character _ which isn't nice especially with deno fmt which only allows 80 characters per line making it harder to read code
