### ISSUE TITLE
Check if resume connection is possible

### ISSUE THREAD

**Issue by binotaliu** [Skillz4Killz/Discordeno#34]
**Describe the bug**
Current the client try to always reconnection to gateway when we got a `WebSocketCloseEvent`:
https://github.com/Skillz4Killz/Discordeno/blob/d612af80d0f3d5d87d9dc3cdd6280e94cd7752a4/module/shard.ts#L109-L112

**Expected behavior**

We should determine if the connection need to resume but not always resume it.  
Some error codes are not recoverable like `4012 Invalid API Version` or `4013 Invalid Intent(s)`.

ref: https://discord.com/developers/docs/topics/opcodes-and-status-codes

**Comment by Skillz4Killz** [comment]
![image](https://user-images.githubusercontent.com/23035000/82148126-76ef6f80-9820-11ea-9c92-17cacb7208b8.png)
 @binotaliu Let me know if I am missing any codes you would like to handle differently.

**Comment by Skillz4Killz** [comment]
I'm gonna leave this issue open but i have merged the PR so the users can have better error handling until tomorrow. If you see anything i missed let me know here or send another pr for it please 🙏

**Comment by Skillz4Killz** [comment]
Havent seen any issues yet so this looks good to close
