### ISSUE TITLE
mod.ts?

### ISSUE THREAD

**Issue by alex-vg** [Skillz4Killz/Discordeno#40]
I stumbled over your neat discord lib and it sounds promising.
But why isn't the mod.ts exporting stuff from the module but instead calling Client()?

e.g. https://deno.land/std/async/mod.ts

**Comment by Skillz4Killz** [comment]
@alex-vg Hi  👋 

So the `mod.ts` file is just for debugging purposes that helps me easily add features and test them before i deploy them. It's never meant to be used. Once the library has been well tested and thoroughly completed i will remove the mod.ts file entirely. While we still need the `--unstable` flag for things inside deno I need to be able to easily test on the fly without pushing code then pulling it in my bot and etc...

When you use the lib to create the bot all you do is `createClient(yourOptions)`. My advice is to check out one of the boilerplate/frameworks and you can get the base of a bot built for you to start with.

Hope that help clarifies it

**Comment by resynth1943** [comment]
Yeah, the mod.ts is for debugging purposes only. Me and Skillz use it :-)

**Comment by alex-vg** [comment]
I don't think removing the mod.ts is a great idea, since you have to import something from the lib and that's where people look take a look.
A lot of other libraries points out what to import by using the mod.ts and I would expect the `createClient` in the mod.ts if that's what I need to use.

**Comment by fox-cat** [comment]
i agree with @alex-vg here; mod.ts is the standard place for modules to export stuff so it would make sense to use that & all

**Comment by Skillz4Killz** [comment]
> I don't think removing the mod.ts is a great idea, since you have to import something from the lib and that's where people take a look.

I'm not entirely opposed to having a mod.ts file that exports everything. I just mean that it isn't entirely necessary imo. Realistically speaking, you can achieve the same result with a deps.ts file which you can add or have it in a boilerplate(which i plan to add). Until now everyone i know using this lib used the boilerplate and never had this issue. I do understand it could help i just thought exporting who knows how many things functions from mod.ts would be bad. The amount of types/interfaces/structures/modules/etc... It's just gonna make mod.ts be a mess and add duplicate code to maintain. 

In my opinion, a better README explanation should suffice and tell people how to import createClient better

> A lot of other libraries points out what to import by using the mod.ts and I would expect the `createClient` in the mod.ts if that's what I need to use.

I'm not sure about other libs as I haven't tested them myself yet but when you code with Discordeno and try to import something, it will auto-import everything whenever you need it. You won't really have trouble trying to go "which file do i import Message or Member from?". It's all automated. The only time this happens is with createClient but if you use one of the boilerplates all that is handled for you entirely. I suppose I should consider adding a section on the README about what to do to start a bot if you don't want to use the boilerplate which could explain this whole thing.

> mod.ts is the standard place for modules to export stuff so it would make sense to use that & all

I do understand that part but it's just unnecessary and duplicate code in my opinion. I like to have DRY code. All of these exports are already being exported from their own files.

---

All that said if any of you want to send a PR to change it like I said above I am not entirely against it. I just feel it's unnecessary. But if it helps you all then go for it! I'll happily accept it.

**Comment by fox-cat** [comment]
it's not "duplicate code" to just... `export x from "y"` i feel
mod.ts is a standard and would be better especially if you dont have any readme showing where to import the main stuff from

**Comment by alex-vg** [comment]
...or `export * from "y"`

**Comment by fox-cat** [comment]
mhmm... importing a bunch of stuff from different places for a single module on the user end feels a lot more like "duplicate code"..

**Comment by Skillz4Killz** [comment]
Our of curiosity why do you feel that exporting something that's already exported is not duplicate and redundant?

**Comment by Skillz4Killz** [comment]
> mhmm... importing a bunch of stuff from different places for a single module on the user end feels a lot more like "duplicate code"..

On the user end this is just `deps.ts` which will be part of the boilerplate

**Comment by fox-cat** [comment]
do you think
```ts
import { x } from "placeone"
import { y } from "placetwo"
import { z } from "placethree"
import { w } from "placefour"
```
instead of just...
```ts
import { x, y, z, w } from "oneplace"
```
on the user-end is worth having a little bit of "duplicate code" to export stuff from a single place?

**Comment by Skillz4Killz** [comment]
@fox-cat That's a fair point but isn't that just a deps.ts 🤔

**Comment by fox-cat** [comment]
what?
also - sure, your module, you should handle exports how you want - but having a `mod.ts` that doesn't export anything on a module is confusing - if it's a test file, i would rename to `test.ts` or something

**Comment by alex-vg** [comment]
> @fox-cat That's a fair point but isn't that just a deps.ts 🤔

Yeah, just another name, but `mod.ts` seems to be default in deno. But I could not find a best practice or anything.

**Comment by fox-cat** [comment]
deps.ts is what the user would use to import a bunch of stuff so they dont need janky links
(e.g. export.ts)
```ts
export { x, y, z } from "place"
export { w } from "place1"
export { h, j } from "place2""
```
then in their app.ts or whatever
```ts
import { x, y, z, w, h, j } from "./deps.ts"
```

`mod.ts` is what the default/ "standard" seems to be in deno for exporting stuff in modules, but it's just that, a standard, no need to conform to it

**Comment by Ryaangu** [comment]
Isn't `deps.ts` for importing dependencies?

**Comment by Skillz4Killz** [comment]
@alex-vg @fox-cat @Ryaangu Let me know if #41 is enough to help. I still feel it's a bit unnecessary. I am more than happy to support it if you all feel this way. 

Just please be patient with me, like I said in the README this lib was made as a way for me to learn and try new things, it was built with my own tastes and my needs. If all of you feel this is useful to you when you use discordeno then 100% that is how it'll be 👍

**Comment by fox-cat** [comment]
as i mentioned before there's no need to conform to the standards;
it's just confusing having a `mod.ts` that exports nothing.

it also helps for documentation purposes (at least, with `doc.deno.land`) to have a single file that exports everything, however if you had a readme (or similar) that documented everything that was exported and such and where to import them from, that would suffice too

having a `mod.ts` that exports everything is an opinionated stance; and since this is your module, it's your opinion that should count most. i don't want you to feel like you're forced to do this because you're not - it's just an opinion and standard to have a single file export most things in a module, (namely, a `mod.ts` file)

**Comment by zeroxs** [comment]
For what it's worth though, not conforming to standards creates confusion such as this here. Where everywhere else uses mod.ts for a specific purpose, that is not followed and issues created to ask what's going on and this thread now exists. Unless there's a good reason to not conform, why not just do it?

**Comment by alex-vg** [comment]
> @alex-vg @fox-cat @Ryaangu Let me know if #41 is enough to help. I still feel it's a bit unnecessary. I am more than happy to support it if you all feel this way.
> 
> Just please be patient with me, like I said in the README this lib was made as a way for me to learn and try new things, it was built with my own tastes and my needs. If all of you feel this is useful to you when you use discordeno then 100% that is how it'll be 👍

Awesome, that's what I need. Thank you!

**Comment by Skillz4Killz** [comment]
Thought id share this here: A good read on why using mod.ts or deps.ts is a bad idea and bad practice

https://dev.to/wongjiahau/why-deps-ts-and-mod-ts-is-bad-in-deno-bjo
