### ISSUE TITLE
[Vote]: Preferred Versioning System

### ISSUE THREAD

**Issue by Skillz4Killz** [Skillz4Killz/Discordeno#44]
Hello 👋 

This issue is just to collect feedback from users of this module to learn about how the 2 versioning system are taken by end users. If you prefer the SemVer versioning for this module leave a 👍 on this issue and if you prefer the automated versioning system leave a ❤️ on this issue.

![image](https://user-images.githubusercontent.com/23035000/82389905-4ddf0280-9a0b-11ea-85db-a23ffdefbf83.png)

If you have any other comments feel free to leave them below as we go through this experiment on which versioning system is better for developers.

**Note:** Please only base your vote/opinions on this module alone. Do not base it on the industry standard or npm or node or anything. This experiment is to see how any developer would feel using this library in a versioning system without MINOR and PATCH system.

**Comment by rahul-sundaresan** [comment]
What are the pros/cons of the versioning systems?

**Comment by Skillz4Killz** [comment]
@rahul-sundaresan  SemVer means more manual work for you to update code but a more secure module.
Automated means almost no manual work for you to update code but a less secure module.

To understand that, SemVer makes it so you are using specific Release versions. In your code, you would do this by targeting the `..../Skillz4Killz/Discordeno/v4.0.0/....` in order to use it. Whenever I make a small bug fix or new feature that does not break your code it would be released in a new release such as today's release of `v4.0.1`. This means you have to manually update your code to get these latest improvements. Until you do, you may have bugs or possibly missing features. The good part about SemVer is that if I make a mistake that could potentially make the code worse, it's a lot easier to move back to a proper version with SemVer.

The automated version would just simply be installed as soon as you reloaded cache for deno because it uses the branch itself as its url `.../Skillz4Killz/Discordeno/v4/....`. For example, when i start bots I use a script that reloads cache and restarts the bot making it so i am always using the latest code. Deno makes this possible because it can pull the latest code from any URL even github. So using Github branches to it's peak I create a branch for each version. These versions simply update automatically and you dont have to worry about updating. The only time you need to update is when you bump a MAJOR version like from v4 to v5. Because these may need you to make changes in your code. Note, even the good part about SemVer can be slightly removed by just locking a certain commit as well using this method.

At the end of the day, I think both systems can work and I am curious how everyone feels about them. I will be trying my best to maintain both systems so this isn't a pick one situation. This is just an experiment to try something different than semver.

**Comment by Suyashtnt** [comment]
I think you should do a mixture of both. so maybe make the `V4` only idea `/BreakingVersion` and the current one will be `VBreak.Major.Minor`.
