### ISSUE TITLE
Lack of usage of classes & event emitters

### ISSUE THREAD

**Issue by itslukej** [Skillz4Killz/Discordeno#48]
From the README:
> - Avoid as many headaches and issues related to `class` and `this`
> - Avoid EventEmitter to not have potential of memory leaks or bot crashes because of too many listeners or other silly issues.

Why?

**Comment by Skillz4Killz** [comment]
@itslukej Here is a pretty cool article on it: https://dannyfritz.wordpress.com/2014/10/11/class-free-object-oriented-programming/

One of the best lectures ive ever seen in programming: https://www.youtube.com/watch?v=PSGEjv3Tqo0 by one of the developers who makes JS

**Comment by zorbyte** [comment]
It appears to be a matter of choice when it comes to how you design you library, there are many benefits to each paradigm and they range from amount of boilerplate to methods of encapsulation. The author of this lib uses many different means to achieve what can be achieved with OOP, with minimal headaches such as { ...superObject, otherProperty }. This has no detriment to any aspects of the library and again comes down to the choice of the author.
