### ISSUE TITLE
Support for join and leave in voice channel

### ISSUE THREAD

**Issue by mtwzim** [Skillz4Killz/Discordeno#50]
**Is your feature request related to a problem? Please describe.**
Add support at join and leave voice channel
**Describe the solution you'd like**
https://github.com/Skillz4Killz/Discordeno/blob/master/structures/channel.ts
I saw that there is no support for entering and leaving a voice channel, see line 221. Can this be implemented quickly?

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by Skillz4Killz** [comment]
Sadly, it is not possible to do anything in the voice channel besides joining and leaving. Deno doesn't support the necessary tools to make music functionality work.
