### ISSUE TITLE
Event: voiceChannelJoin not handling

### ISSUE THREAD

**Issue by mtwzim** [Skillz4Killz/Discordeno#51]
**Describe the bug**
Event: voiceChannelJoin not handling

**Expected behavior**
Events of user join in voice channel

**Screenshots**
![image](https://user-images.githubusercontent.com/42474938/82738263-c5af7480-9d0c-11ea-9652-160fcb937d6a.png)
![image](https://user-images.githubusercontent.com/42474938/82738268-d102a000-9d0c-11ea-816b-6643d9b13708.png)

**Comment by Skillz4Killz** [comment]
This is probably happening because the member was not cached before they joined the voice channel. Let me see if i can try and find a better way to handle this type of situation

**Comment by Skillz4Killz** [comment]
Fixed this bug and deployed to master. Will be released in a new release later today. If anyone needs this at the moment, please use `master` branch.
