### ISSUE TITLE
Simplest example throws `REQUEST_CLIENT_ERROR`

### ISSUE THREAD

**Issue by amatiasq** [Skillz4Killz/Discordeno#57]
**Describe the bug**
Simplest example throws `REQUEST_CLIENT_ERROR`. Also happened when using https://github.com/Skillz4Killz/Discordeno-bot-template

**To Reproduce**
1. Go to https://repl.it/@amatiasq/discordeno-bug
3. See error

**Expected behavior**
I don't know, I was exploring the tool. It should not crash

**Screenshots**
![Screenshot 2020-06-04 at 09 46 47](https://user-images.githubusercontent.com/1533589/83729719-51e46480-a648-11ea-8401-bd6258bc5051.png)

**Additional context**
https://repl.it/@amatiasq/discordeno-bug

**Comment by amatiasq** [comment]
The ID and token in both the screenshot and the REPL are of a new bot I created to show the issue, I'll remove it once this is fixed.

**Comment by amatiasq** [comment]
I'd mixed `botID` and `token` values in the REPL and the screenshot, I've fixed the REPL example but still happens:

https://repl.it/@amatiasq/discordeno-bug

**Comment by Skillz4Killz** [comment]
I would recommend going to the Discord Dashboard and regenerating your token as you may have shared it here. In regards to the token, are you sure you copied it entirely? That looks way too small to be a valid token.

You also need to provide atleast 1 intent as without any intents your bot will never be able to do anything. @amatiasq

**Comment by TTtie** [comment]
@amatiasq The `token` you provided is actually a client secret. You want to obtain your bot token from here:
![image](https://user-images.githubusercontent.com/17570452/83753844-4bb3af80-a66b-11ea-8e26-66bd6ebb33d9.png)

**Comment by amatiasq** [comment]
@Skillz4Killz thanks for your concern, as I said in [the last message](https://github.com/Skillz4Killz/Discordeno/issues/57#issuecomment-638691773) I've created this token only to share it here.

I know the token is shorter than others I have but that's what Discord Dashboard gives me. I've created another application and the token is the same length, maybe they changed the token length?

![Screenshot 2020-06-04 at 14 20 12](https://user-images.githubusercontent.com/1533589/83756143-e95cae00-a66e-11ea-8382-23c57b03a8d7.png)

In my real code I have some intents but here I was trying to provide the smallest snippet possible. Anyway I've added the intent back, you can see the error still ocurs.

In any case I don't see how any of those issues can produce a `MethodNotAllowed` error:
https://github.com/Skillz4Killz/Discordeno/blob/master/module/requestManager.ts#L203-L204

**Comment by amatiasq** [comment]
Thanks @TTtie! that was the issue indeed! so that explains why the "token" was shorter, then.

So for future references check [TTie's response](https://github.com/Skillz4Killz/Discordeno/issues/57#issuecomment-638802542)

I'm removing the application now.
