### ISSUE TITLE
Create a good Events API.

### ISSUE THREAD

**Issue by resynth1943** [Skillz4Killz/Discordeno#7]
This could either be with Observables, or something else. Let's think about it.

We need a system where users can listen to events.

**Comment by Skillz4Killz** [comment]
The current idea i have as a rough first draft is that when an event is sent by discord through the websocket we just run a function on the client.

client.eventHandlers.guildMemberAdd() for example

This would allow the end users to overwrite the functions as they wish.

**Comment by resynth1943** [comment]
Hmm. I'm not opposed to that, as it would be a lot more complex then an `EventEmitter`-like system, where you have to think about ordering and such.

**Comment by Skillz4Killz** [comment]
Complete. Needs refactoring, debugging and a bit of touchup but the base is complete.
