### ISSUE TITLE
Unable to create guild channel with specified channel type

### ISSUE THREAD

**Issue by molteber** [Skillz4Killz/Discordeno#70]
**Describe the bug**
When creating a guild channel, a bad request is returned from discord.

**To Reproduce**
1. When connected to a guild, create guild channel with specific type.
2. See error

**Expected behavior**
Channel should be created without any issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/8125386/87781739-8c3d4600-c831-11ea-899e-74f1a33e8341.png)

**Additional context**
Using the latest release, 6.1.2.
I'm creating the channel specificly with type 2 for voice:
```ts
const newChannel = await createGuildChannel(guild, 'Random-voice-name', {
  type: ChannelTypes.GUILD_VOICE,
});
``` 

After some debugging, it looks like the error is here: https://github.com/Skillz4Killz/Discordeno/blob/master/handlers/guild.ts#L112

Output of the request body shows that it sends `type: "GUILD_VOICE"` instead of `type: 2`

**Comment by Skillz4Killz** [comment]
@molteber Hey I just deployed a fix to `master` and to the `v6` branch. I have tested it on my end and it does work now. Good catch! I can't believe i missed that 🤦 

Please let me know if you see any issues. Will make a new release later today once i get some time as there are a lot of new details that need to be explained in the next release.

**Comment by molteber** [comment]
Superb! Thanks for the quick fix! :)
