### ISSUE TITLE
Voice events does not work as expected

### ISSUE THREAD

**Issue by molteber** [Skillz4Killz/Discordeno#74]
**Describe the bug**
Abnormalities in voice events. I've set up 3 events, joined, left and switched voice channels.
It looks like it doesn't update the current voice channel for a given user.

By the looks of the events, I also assume the current voice channels are somewhat cached, which is not updated at all places. But can't tell for sure

**To Reproduce**
1. Join VC 1. (Join VC 1 event emitted)
2. Leave VC 1. (Leave VC 1 event emitted)
3. Join VC 2. (No join event is emitted, but switch from VC 1 to VC 2 is emitted)
4. Join VC 1. (No events are emitted)
5. Join VC 2. (Switch from VC 1 to VC 2 event is emitted)
6. Leave VC 2. (Leave VC 1 event emitted, not VC 2)

**Expected behavior**
Expect to see correct join and leave events.

**Screenshots**
![image](https://user-images.githubusercontent.com/8125386/87803097-59577a00-c852-11ea-9f52-ded7c0f75bfa.png)

**Additional context**
Using the latest v6 branch

**Comment by Skillz4Killz** [comment]
@molteber Good catch, amazing debugging and reporting! The details you provide always help make it so easy to find and fix the issue <3 This is now fixed and deployed in `master` and `v6` branches. Will be part of release later today.
