### ISSUE TITLE
processQueue() exceeds maximum call stack size

### ISSUE THREAD

**Issue by RubenArtmann** [Skillz4Killz/Discordeno#90]
**Describe the bug**
Calling addReaction (or presumably other functions) to fast results in [processQueue](https://github.com/Skillz4Killz/Discordeno/blob/e84823f006832809408f679fb464ec6ec60082fd/src/module/requestManager.ts#L37) calling itself until it exceeds the stack size limit. Waiting a second between calls "solves" the issue.

**To Reproduce**
1. run: 
```
import Client from "https://raw.githubusercontent.com/Skillz4Killz/Discordeno/master/src/module/client.ts";
import { addReaction } from "https://raw.githubusercontent.com/Skillz4Killz/Discordeno/master/src/handlers/message.ts";
import { Intents } from "https://raw.githubusercontent.com/Skillz4Killz/Discordeno/master/src/types/options.ts";

Client({
	token: "<bot-token>",
	intents: [Intents.GUILD_MESSAGES, Intents.GUILDS, Intents.GUILD_MESSAGE_REACTIONS],
	eventHandlers: {
		ready: ()=>{console.log("Ready!");},
		messageCreate: async (m)=>{
			if (m.content === "!react") {
				addReaction(m.channelID,m.id,"🔼");
				addReaction(m.channelID,m.id,"🔽");
				addReaction(m.channelID,m.id,"◀️");
				addReaction(m.channelID,m.id,"▶️");
			}
		}
	}
});
```
2. send !react on discord
3. crash:
```
error: Uncaught RangeError: Maximum call stack size exceeded
    const request = queue.shift();
                          ^
    at Array.shift (<anonymous>)
    at processQueue (requestManager.ts:39:27)
    at processQueue (requestManager.ts:60:21)
    at processQueue (requestManager.ts:60:21)
    at processQueue (requestManager.ts:60:21)
    at processQueue (requestManager.ts:60:21)
    at processQueue (requestManager.ts:60:21)
    at processQueue (requestManager.ts:60:21)
    at processQueue (requestManager.ts:60:21)
    at processQueue (requestManager.ts:60:21)
```

**Expected behavior**
No crash (and all reactions of the bot on discord)

**Screenshots**
chat-history in discord
![Screenshot from 2020-08-09 19-50-56](https://user-images.githubusercontent.com/69248730/89738533-af969200-da79-11ea-9a2b-b2fdcced4e0d.png)

**Additional context**
 broken on branch: master

if I have enough time I want to clone the repo and try wrapping the recursive call into queueMicrotask (similar to process.nextTick in Node) or setTimeout.

**Comment by Skillz4Killz** [comment]
@RubenArtmann Thank you for the bug report. I think this should be patched now. I also got an idea when i saw your code, not sure if you would like it but i also added a `addReactions()` that can be used to add multiple reactions.

```ts
// Will add all reactions as fast as possible without care of order
addReactions(channelID, messageID, reactionsStringArray)
// Will add all reactions one by one so it is in order
addReactions(channelID, messageID, reactionsStringArray, true)
```
